### ISSUE TITLE
seperate the src layout into headers

### ISSUE THREAD

**Issue by rurban** [rurban/safeclib#12]
and extensions:
str,extstr,mem,extstr,io,misc,os,stdlib,wchar

**Comment by jeremyhannon** [comment]
when you say "seperate the src layout into headers", would there be one .h for every .c afterwards? This would help since we use [Unity/Ceedling](http://www.throwtheswitch.org/#download-section) for unit testing and Ceedling makes some file structure assumptions. (btw I'd be ok with rolling all string functions into a single `safe_str_lib.c` file instead of one-function-per-header)

**Comment by rurban** [comment]
done with 480d59c7f77dc75df4021ea0f7356e7205e2e713

the headers stay of course the same. we will not change the API.
it's only the internal src layout.

**Comment by rurban** [comment]
I didn't really read your request, sorry. One h per c makes sense in your case. But for safeclib it would be massive overkill to include all single h files. Do the 2 new splits unsafe and extensions help?

**Comment by jeremyhannon** [comment]
ok, I understand your file structure preference.

Yes, separating the unsafe vs extensions seems wise. In our structure we've separated what is in the C11AnnexK standard vs other related functions we've added (particularly, truncating versions since the C11AnnexK returns an empty string if the destination is too small). That way the file structure makes clear what is from the standard and what deviates.
