### ISSUE TITLE
Why you say snprintf_s is unsafe std C11 function?

### ISSUE THREAD

**Issue by chenlilong84** [rurban/safeclib#35]
Hi rurban,

      From configure file, '--enable-unsafe'  flag will include unsafe std C11 functions, could you tell me why these functions are unsafe? based on what? thanks!

Regards
chenlilong84

**Comment by rurban** [comment]
See the documentation of these functions. E.g.
https://rurban.github.io/safeclib/doc/safec-3.1/d8/d3c/snprintf__s_8c.html
*Instead of being printed, the content is stored in dest. More than dmax - 1 characters might be written, so this variant is unsafe! Always use sprintf_s instead.*

With truncation the final \0 might get lost.

**Comment by chenlilong84** [comment]
`sprintf_s(char * restrict dest, rsize_t dmax, const char * restrict fmt, ...)`
`snprintf_s(char * restrict dest, rsize_t dmax, const char * restrict fmt, ...)`
So you mean sprintf_s is more safer than snprintf_s, because sprintf_s checks argument length should less than dmax, but snprintf_s has no check for it, if argument length is greater than dmax, null-terminated will be lost, right?

**Comment by rurban** [comment]
exactly

**Comment by rurban** [comment]
I made the 4 truncating versions now safe, putting a \0 at the end when truncating. See #52
