### ISSUE TITLE
On windows 12 getting crash with fprintf_s() with latest libsafec-3.5.1.a

### ISSUE THREAD

**Issue by tharunbandikolla** [rurban/safeclib#94]
Hi Team,

We Included libsafec-3.5.1.a in our binaries. 
Its getting crash in the function fprintf_s() and its happening only in Windows 2k12 R2

Thanks,
Tharun

**Comment by DBJDBJ** [comment]
## R U sending messages from the future?

![image](https://user-images.githubusercontent.com/145155/108209517-affb9e00-712a-11eb-8d4c-ca2a93e3a9f8.png)

**Comment by tharunbandikolla** [comment]
Sorry, i didn't understand that.

**Comment by DBJDBJ** [comment]
> Sorry, i didn't understand that.

Windows 12 is not out yet :) Just kidding. I assume you meant Windows Server 2012.

Can you please post some code that is crashing each time you run it with `libsafec-3.5.1a` ? As small as possible, please.

**Comment by rurban** [comment]
Show us the usage where it crashes. All the args. 

Some parts of fprintf_s are not implemented yet according to the specs. But on Windows I just use the native variant which behaves differently with buffers like %s.

**Comment by DBJDBJ** [comment]
> Show us the usage where it crashes. All the args.
> 
> Some parts of fprintf_s are not implemented yet according to the specs. But on Windows, I just use the native variant which behaves differently with buffers like %s.

If you want to know what is really going on inside the WIN code and your C/C++ you need to use [SEH](https://docs.microsoft.com/en-us/cpp/cpp/structured-exception-handling-c-cpp?view=msvc-160 )and [Minidumps](https://docs.microsoft.com/en-us/windows/win32/api/minidumpapiset/nf-minidumpapiset-minidumpwritedump).

The only feasible compiler in that scenario is cl.exe. Since in the context of "safe" on WIN32 one really wants to build using the /kernel switch.

**Comment by tharunbandikolla** [comment]
![image](https://user-images.githubusercontent.com/78307477/108302605-5185fc80-71ca-11eb-8002-93dc04f62315.png)

And we are not directly using the function, we are using this via libxml2 library functions.

**Comment by tharunbandikolla** [comment]
Sorry, i think this might be an issue with libxml2 library itself.
